### ISSUE TITLE
generalize election equations? pyeq2-like line-fitting utility?

### ISSUE THREAD

**Issue by thetoxicarcade** [congredi/spec#19]
Is there a syntax for representing ranked choice voting, to differentiate a party list from a proportional, down to the nitty gritty like droop vs hare quotas?

For example, in Python Pyeq2 can perform line-fitting on equation strings "Y=2ax+4b+c", finding the coefficient values given a dataset.

Is there a preferred mathematical/procedural abstraction for voting, or, even better, a syntax or formular that can be evaulated in multiple computer languages (so as to avoid ambiguity between implementing it in python / js, etc).

It would be a good reference to have the exact formula on hand, better to be able to transcompile that into code precisely, and even better to have a library that simply runs the computation.

Terminology needed :/

**Comment by Thetoxicarcade** [comment]
Evaluating voting equations: https://en.wikipedia.org/wiki/Voting_system#Evaluating_voting_systems_using_criteria

* Graph theorem 1: https://en.wikipedia.org/wiki/Gibbard%E2%80%93Satterthwaite_theorem
* Arrow's Impossibility Theorem: https://en.wikipedia.org/wiki/Arrow%27s_impossibility_theorem
* Condorcet methods: https://en.wikipedia.org/wiki/Condorcet_method
* Shulze https://en.wikipedia.org/wiki/Schulze_method

so matrix & directed graph notations seem about right for voting theorems, but maybe not for individual vote counting methods.
