### ISSUE TITLE
en <-> ISO 639-1 libs for JS/PY?

### ISSUE THREAD

**Issue by thetoxicarcade** [congredi/spec#20]
the [documents][https://github.com/congredi/spec/blob/3400d31ce323ac7d98d196df8dcb4e738e667072/computations/blobs.md#documents] section lists using two letter language codes as part of the spec.

What's a good library / code snippet to use for that in JavaScript & Python?

**Comment by Thetoxicarcade** [comment]
LangCodes or a raw dictionary? Babelfish / ISO_LANG_CODES are either bad libraries or have a debian dependency...

For langcodes:
```
Language.get('fr').language_name() # "French"
Language.get('fr').language_name('fr') # 'français'
Language.get('fr').language_name('en') # "French"
Language.get('es').autonym() # 'français'
```

For JavaScript, possibly locale-code, [iso-639-1](https://github.com/meikidd/iso-639-1) or this [gist](https://gist.github.com/mirontoli/4722797)?

For Locale-code:
```
console.log(LocaleCode.getLanguageCode('en-US')); // 'en'
console.log(LocaleCode.getLanguageName('zh-CN')); // 'Chinese'
console.log(LocaleCode.getLanguageNativeName('zh-CN')); // '中文'
```
we have to end in the country name??
